name: oppdrift
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  #codecov
  coverage: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.3
  built_value_generator: ^6.4.0

flutter:
  uses-material-design: true