name: oppdrift
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^2.0.7

  cupertino_icons: ^0.1.2

  #codecov
  coverage: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.3
  built_value_generator: ^6.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/oppdrift-logo.png
    - assets/images/oppdrift-transparent.png
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-Light-BT.ttf
          weight: 300
        - asset: assets/fonts/Futura-Light-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Futura-Book.ttf
          weight: 400
        - asset: assets/fonts/Futura-Book-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Futura-Medium.ttf
          weight: 500
        - asset: assets/fonts/Futura-Bold.ttf
          weight: 600